### PR TITLE
docs: update ignoreEvalErrors option in docs/demo

### PR DESCRIPTION
**Pull request by 80avin**
## PR description

* update browser demo to include ignoreEvalErrors option and minor enhancements
* update docs
* Update cli test to be compatible with node20.
   * node 20 prints stack trace differently than node 16. This was causing cli test to fail. Removing the stack trace from test assertion to fix this break.

## Checklist

- [ ] - Added tests
- [x] - Ran `npm test`, ensuring linting passes
- [x] - Adjust README documentation if relevant

### CODE REVIEW

**Comment by brettz9** [comment]
Looks good to me. But first, @80avin , did you receive an email from me (2024/9/13, 7:16 PM)? Or did it go to junk?

**Comment by 80avin-sw** [comment]
Just checked, Yes I received your email.

**Review by brettz9 — APPROVED** [review]

**Comment by 80avin** [comment]
Just checked, Yes I received your email.
Can't commit a timeline, but I'll do the change

> _PS: I deleted previous comment as it was made from my corporate account. Copy pasted into this comment._

**Comment by brettz9** [comment]
@80avin : I went ahead and made the fix and released as part of v10.0.0. Still, if it's ok with you, it may be good for you to give it a review whenever you might have some time.

**Pull request merged**
